#!/bin/bash

HTML="/root/Rucoy-bosses/index.html"

function att-repo(){
    cd $HOME/Rucoy-bosses/
    git add .
    git commit -m "update index.html boss status"
    git push origin main
    . boss-status
}

while true; do
#    clear
    echo " Por favor, selecione um servidor :"
    echo ""

    echo "América do Norte:"

    echo " 1) North America 1 '$(
    if [[ $(sed '64q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
        echo -e '\033[0;32mLa Calaca/Haunted Willow\033[0m'
    elif [[ $(sed '64q;d' "$HTML") == *"La Calaca"* ]]; then
        echo -e '\033[0;32mLa Calaca\033[0m'
    elif [[ $(sed '64q;d' "$HTML") == *"Haunted Willow"* ]]; then
        echo -e '\033[0;32mHaunted Willow\033[0m'
    elif [[ $(sed '64q;d' "$HTML") == *"Boss Not Found"* ]]; then
        echo -e '\033[0;31mBoss Not Found\033[0m'
    fi
)'"
    echo " 2) North America 2 '$(
    if [[ $(sed '69q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
    echo -e '\033[0;32mLa Calaca/Haunted Willow\033[0m'
    elif [[ $(sed '69q;d' "$HTML") == *"La Calaca"* ]]; then
        echo -e '\033[0;32mLa Calaca\033[0m'
    elif [[ $(sed '69q;d' "$HTML") == *"Haunted Willow"* ]]; then
        echo -e '\033[0;32mHaunted Willow\033[0m'
    elif [[ $(sed '69q;d' "$HTML") == *"Boss Not Found"* ]]; then
        echo -e '\033[0;31mBoss Not Found\033[0m'
    fi
)'"
    echo " 3) North America 3 '$(
    if [[ $(sed '74q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
        echo -e '\033[0;32mLa Calaca/Haunted Willow\033[0m'
    elif [[ $(sed '74q;d' "$HTML") == *"La Calaca"* ]]; then
        echo -e '\033[0;32mLa Calaca\033[0m'
    elif [[ $(sed '74q;d' "$HTML") == *"Haunted Willow"* ]]; then
        echo -e '\033[0;32mHaunted Willow\033[0m'
    elif [[ $(sed '74q;d' "$HTML") == *"Boss Not Found"* ]]; then
        echo -e '\033[0;31mBoss Not Found\033[0m'
    fi
)'"
    echo " 4) North America 4 '$(
    if [[ $(sed '78q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
        echo -e '\033[0;32mLa Calaca/Haunted Willow\033[0m'
    elif [[ $(sed '78q;d' "$HTML") == *"La Calaca"* ]]; then
        echo -e '\033[0;32mLa Calaca\033[0m'
    elif [[ $(sed '78q;d' "$HTML") == *"Haunted Willow"* ]]; then
        echo -e '\033[0;32mHaunted Willow\033[0m'
    elif [[ $(sed '78q;d' "$HTML") == *"Boss Not Found"* ]]; then
        echo -e '\033[0;31mBoss Not Found\033[0m'
    fi
)'"
    echo " 5) North America 5 '$(
    if [[ $(sed '82q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
        echo -e '\033[0;32mLa Calaca/Haunted Willow\033[0m'
    elif [[ $(sed '82q;d' "$HTML") == *"La Calaca"* ]]; then
        echo -e '\033[0;32mLa Calaca\033[0m'
    elif [[ $(sed '82q;d' "$HTML") == *"Haunted Willow"* ]]; then
        echo -e '\033[0;32mHaunted Willow\033[0m'
    elif [[ $(sed '82q;d' "$HTML") == *"Boss Not Found"* ]]; then
        echo -e '\033[0;31mBoss Not Found\033[0m'
    fi
)'"
    echo " 6) North America 6 '$(
    if [[ $(sed '86q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
        echo -e '\033[0;32mLa Calaca/Haunted Willow\033[0m'
    elif [[ $(sed '86q;d' "$HTML") == *"La Calaca"* ]]; then
        echo -e '\033[0;32mLa Calaca\033[0m'
    elif [[ $(sed '86q;d' "$HTML") == *"Haunted Willow"* ]]; then
        echo -e '\033[0;32mHaunted Willow\033[0m'
    elif [[ $(sed '86q;d' "$HTML") == *"Boss Not Found"* ]]; then
        echo -e '\033[0;31mBoss Not Found\033[0m'
    fi
)'"
    echo ""

    echo "América do Sul:"
    echo " 7) South America 1 '$(
    if [[ $(sed '93q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
        echo -e '\033[0;32mLa Calaca/Haunted Willow\033[0m'
    elif [[ $(sed '93q;d' "$HTML") == *"La Calaca"* ]]; then
        echo -e '\033[0;32mLa Calaca\033[0m'
    elif [[ $(sed '93q;d' "$HTML") == *"Haunted Willow"* ]]; then
        echo -e '\033[0;32mHaunted Willow\033[0m'
    elif [[ $(sed '93q;d' "$HTML") == *"Boss Not Found"* ]]; then
        echo -e '\033[0;31mBoss Not Found\033[0m'
    fi
)'"
    echo " 8) South America 2 '$(
    if [[ $(sed '97q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
        echo -e '\033[0;32mLa Calaca/Haunted Willow\033[0m'
    elif [[ $(sed '97q;d' "$HTML") == *"La Calaca"* ]]; then
        echo -e '\033[0;32mLa Calaca\033[0m'
    elif [[ $(sed '97q;d' "$HTML") == *"Haunted Willow"* ]]; then
        echo -e '\033[0;32mHaunted Willow\033[0m'
    elif [[ $(sed '97q;d' "$HTML") == *"Boss Not Found"* ]]; then
        echo -e '\033[0;31mBoss Not Found\033[0m'
    fi
)'"
    echo " 9) South America 3 '$(
    if [[ $(sed '101q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
        echo -e '\033[0;32mLa Calaca/Haunted Willow\033[0m'
    elif [[ $(sed '101q;d' "$HTML") == *"La Calaca"* ]]; then
        echo -e '\033[0;32mLa Calaca\033[0m'
    elif [[ $(sed '101q;d' "$HTML") == *"Haunted Willow"* ]]; then
        echo -e '\033[0;32mHaunted Willow\033[0m'
    elif [[ $(sed '101q;d' "$HTML") == *"Boss Not Found"* ]]; then
        echo -e '\033[0;31mBoss Not Found\033[0m'
    fi
)'"
    echo "10) South America 4 '$(
    if [[ $(sed '105q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
        echo -e '\033[0;32mLa Calaca/Haunted Willow\033[0m'
    elif [[ $(sed '105q;d' "$HTML") == *"La Calaca"* ]]; then
        echo -e '\033[0;32mLa Calaca\033[0m'
    elif [[ $(sed '105q;d' "$HTML") == *"Haunted Willow"* ]]; then
        echo -e '\033[0;32mHaunted Willow\033[0m'
    elif [[ $(sed '105q;d' "$HTML") == *"Boss Not Found"* ]]; then
        echo -e '\033[0;31mBoss Not Found\033[0m'
    fi
)'"
    echo "11) South America 5 '$(
    if [[ $(sed '109q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
        echo -e '\033[0;32mLa Calaca/Haunted Willow\033[0m'
    elif [[ $(sed '109q;d' "$HTML") == *"La Calaca"* ]]; then
        echo -e '\033[0;32mLa Calaca\033[0m'
    elif [[ $(sed '109q;d' "$HTML") == *"Haunted Willow"* ]]; then
        echo -e '\033[0;32mHaunted Willow\033[0m'
    elif [[ $(sed '109q;d' "$HTML") == *"Boss Not Found"* ]]; then
        echo -e '\033[0;31mBoss Not Found\033[0m'
    fi
)'"
    echo "12) South America 6 '$(
    if [[ $(sed '113q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
        echo -e '\033[0;32mLa Calaca/Haunted Willow\033[0m'
    elif [[ $(sed '113q;d' "$HTML") == *"La Calaca"* ]]; then
        echo -e '\033[0;32mLa Calaca\033[0m'
    elif [[ $(sed '113q;d' "$HTML") == *"Haunted Willow"* ]]; then
        echo -e '\033[0;32mHaunted Willow\033[0m'
    elif [[ $(sed '113q;d' "$HTML") == *"Boss Not Found"* ]]; then
        echo -e '\033[0;31mBoss Not Found\033[0m'
    fi
)'"
    echo "13) South America 7 '$(
    if [[ $(sed '117q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
        echo -e '\033[0;32mLa Calaca/Haunted Willow\033[0m'
    elif [[ $(sed '117q;d' "$HTML") == *"La Calaca"* ]]; then
        echo -e '\033[0;32mLa Calaca\033[0m'
    elif [[ $(sed '117q;d' "$HTML") == *"Haunted Willow"* ]]; then
        echo -e '\033[0;32mHaunted Willow\033[0m'
    elif [[ $(sed '117q;d' "$HTML") == *"Boss Not Found"* ]]; then
        echo -e '\033[0;31mBoss Not Found\033[0m'
    fi
)'"
    echo "14) South America 8 '$(
    if [[ $(sed '121q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
        echo -e '\033[0;32mLa Calaca/Haunted Willow\033[0m'
    elif [[ $(sed '121q;d' "$HTML") == *"La Calaca"* ]]; then
        echo -e '\033[0;32mLa Calaca\033[0m'
    elif [[ $(sed '121q;d' "$HTML") == *"Haunted Willow"* ]]; then
        echo -e '\033[0;32mHaunted Willow\033[0m'
    elif [[ $(sed '121q;d' "$HTML") == *"Boss Not Found"* ]]; then
        echo -e '\033[0;31mBoss Not Found\033[0m'
    fi
)'"
    echo ""

    echo "Europa:"
    echo "15) Europe 1 '$(
    if [[ $(sed '128q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
        echo -e '\033[0;32mLa Calaca/Haunted Willow\033[0m'
    elif [[ $(sed '128q;d' "$HTML") == *"La Calaca"* ]]; then
        echo -e '\033[0;32mLa Calaca\033[0m'
    elif [[ $(sed '128q;d' "$HTML") == *"Haunted Willow"* ]]; then
        echo -e '\033[0;32mHaunted Willow\033[0m'
    elif [[ $(sed '128q;d' "$HTML") == *"Boss Not Found"* ]]; then
        echo -e '\033[0;31mBoss Not Found\033[0m'
    fi
)'"
    echo "16) Europe 2 '$(
    if [[ $(sed '132q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
        echo -e '\033[0;32mLa Calaca/Haunted Willow\033[0m'
    elif [[ $(sed '132q;d' "$HTML") == *"La Calaca"* ]]; then
        echo -e '\033[0;32mLa Calaca\033[0m'
    elif [[ $(sed '132q;d' "$HTML") == *"Haunted Willow"* ]]; then
        echo -e '\033[0;32mHaunted Willow\033[0m'
    elif [[ $(sed '132q;d' "$HTML") == *"Boss Not Found"* ]]; then
        echo -e '\033[0;31mBoss Not Found\033[0m'
    fi
)'"
    echo "17) Europe 3 '$(
    if [[ $(sed '136q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
        echo -e '\033[0;32mLa Calaca/Haunted Willow\033[0m'
    elif [[ $(sed '136q;d' "$HTML") == *"La Calaca"* ]]; then
        echo -e '\033[0;32mLa Calaca\033[0m'
    elif [[ $(sed '136q;d' "$HTML") == *"Haunted Willow"* ]]; then
        echo -e '\033[0;32mHaunted Willow\033[0m'
    elif [[ $(sed '136q;d' "$HTML") == *"Boss Not Found"* ]]; then
        echo -e '\033[0;31mBoss Not Found\033[0m'
    fi
)'"
    echo "18) Europe 4 '$(
    if [[ $(sed '140q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
        echo -e '\033[0;32mLa Calaca/Haunted Willow\033[0m'
    elif [[ $(sed '140q;d' "$HTML") == *"La Calaca"* ]]; then
        echo -e '\033[0;32mLa Calaca\033[0m'
    elif [[ $(sed '140q;d' "$HTML") == *"Haunted Willow"* ]]; then
        echo -e '\033[0;32mHaunted Willow\033[0m'
    elif [[ $(sed '140q;d' "$HTML") == *"Boss Not Found"* ]]; then
        echo -e '\033[0;31mBoss Not Found\033[0m'
    fi
)'"
    echo "19) Europe 5 '$(
    if [[ $(sed '144q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
        echo -e '\033[0;32mLa Calaca/Haunted Willow\033[0m'
    elif [[ $(sed '144q;d' "$HTML") == *"La Calaca"* ]]; then
        echo -e '\033[0;32mLa Calaca\033[0m'
    elif [[ $(sed '144q;d' "$HTML") == *"Haunted Willow"* ]]; then
        echo -e '\033[0;32mHaunted Willow\033[0m'
    elif [[ $(sed '144q;d' "$HTML") == *"Boss Not Found"* ]]; then
        echo -e '\033[0;31mBoss Not Found\033[0m'
    fi
)'"
    echo "20) Europe 6 '$(
    if [[ $(sed '148q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
        echo -e '\033[0;32mLa Calaca/Haunted Willow\033[0m'
    elif [[ $(sed '148q;d' "$HTML") == *"La Calaca"* ]]; then
        echo -e '\033[0;32mLa Calaca\033[0m'
    elif [[ $(sed '148q;d' "$HTML") == *"Haunted Willow"* ]]; then
        echo -e '\033[0;32mHaunted Willow\033[0m'
    elif [[ $(sed '148q;d' "$HTML") == *"Boss Not Found"* ]]; then
        echo -e '\033[0;31mBoss Not Found\033[0m'
    fi
)'"
    echo ""

    echo "Ásia:"
    echo "21) Asia 1 '$(
    if [[ $(sed '155q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
        echo -e '\033[0;32mLa Calaca/Haunted Willow\033[0m'
    elif [[ $(sed '155q;d' "$HTML") == *"La Calaca"* ]]; then
        echo -e '\033[0;32mLa Calaca\033[0m'
    elif [[ $(sed '155q;d' "$HTML") == *"Haunted Willow"* ]]; then
        echo -e '\033[0;32mHaunted Willow\033[0m'
    elif [[ $(sed '155q;d' "$HTML") == *"Boss Not Found"* ]]; then
        echo -e '\033[0;31mBoss Not Found\033[0m'
    fi
)'"
    echo "22) Asia 2 '$(
    if [[ $(sed '159q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
        echo -e '\033[0;32mLa Calaca/Haunted Willow\033[0m'
    elif [[ $(sed '159q;d' "$HTML") == *"La Calaca"* ]]; then
        echo -e '\033[0;32mLa Calaca\033[0m'
    elif [[ $(sed '159q;d' "$HTML") == *"Haunted Willow"* ]]; then
        echo -e '\033[0;32mHaunted Willow\033[0m'
    elif [[ $(sed '159q;d' "$HTML") == *"Boss Not Found"* ]]; then
        echo -e '\033[0;31mBoss Not Found\033[0m'
    fi
)'"
    echo "23) Asia 3 '$(
    if [[ $(sed '163q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
        echo -e '\033[0;32mLa Calaca/Haunted Willow\033[0m'
    elif [[ $(sed '163q;d' "$HTML") == *"La Calaca"* ]]; then
        echo -e '\033[0;32mLa Calaca\033[0m'
    elif [[ $(sed '163q;d' "$HTML") == *"Haunted Willow"* ]]; then
        echo -e '\033[0;32mHaunted Willow\033[0m'
    elif [[ $(sed '163q;d' "$HTML") == *"Boss Not Found"* ]]; then
        echo -e '\033[0;31mBoss Not Found\033[0m'
    fi
)'"
    echo "24) Asia 4 '$(
    if [[ $(sed '167q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
        echo -e '\033[0;32mLa Calaca/Haunted Willow\033[0m'
    elif [[ $(sed '167q;d' "$HTML") == *"La Calaca"* ]]; then
        echo -e '\033[0;32mLa Calaca\033[0m'
    elif [[ $(sed '167q;d' "$HTML") == *"Haunted Willow"* ]]; then
        echo -e '\033[0;32mHaunted Willow\033[0m'
    elif [[ $(sed '167q;d' "$HTML") == *"Boss Not Found"* ]]; then
        echo -e '\033[0;31mBoss Not Found\033[0m'
    fi
)'"
    echo ""
    echo "25) Adicionar novo boss"
    echo ""

    read -p "Opção: " option

    case $option in
        1)
        echo "Você selecionou North America 1"

        # Verifica se ambos os bosses estão presentes
            if [[ $(sed '64q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
            echo "Ambos os bosses estão presentes. Qual você deseja remover?"
            echo "1) La Calaca"
            echo "2) Haunted Willow"
            read -p "Selecione uma opção (1 ou 2): " boss_option

                if [[ $boss_option -eq 1 ]]; then
                    # Remover La Calaca e manter Haunted Willow
                    sed -i '64s/La Calaca\/Haunted Willow/Haunted Willow/' $HTML
                    echo "La Calaca foi removido."
                elif [[ $boss_option -eq 2 ]]; then
                    # Remover Haunted Willow e manter La Calaca
                    sed -i '64s/La Calaca\/Haunted Willow/La Calaca/' $HTML
                    echo "Haunted Willow foi removido."
                else
                    echo "Opção inválida."
                fi
            elif [[ $(sed '64q;d' "$HTML") == *"La Calaca"* ]]; then
                sed -i '64s/La Calaca/Boss Not Found/' $HTML
                sed -i '64s/color: rgb(0, 255, 0);/color: red;/' $HTML
                echo "O status de North America 1 foi alterado"
            elif [[ $(sed '64q;d' "$HTML") == *"Haunted Willow"* ]]; then
                sed -i '64s/Haunted Willow/Boss Not Found/' $HTML
                sed -i '64s/color: rgb(0, 255, 0);/color: red;/' $HTML
            fi
        
            att-repo
            break;;
        2)
            echo "Você selecionou North America 2"

            if [[ $(sed '69q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
            echo "Ambos os bosses estão presentes. Qual você deseja remover?"
            echo "1) La Calaca"
            echo "2) Haunted Willow"
            read -p "Selecione uma opção (1 ou 2): " boss_option

                if [[ $boss_option -eq 1 ]]; then
                    # Remover La Calaca e manter Haunted Willow
                    sed -i '69s/La Calaca\/Haunted Willow/Haunted Willow/' $HTML
                    echo "La Calaca foi removido."
                elif [[ $boss_option -eq 2 ]]; then
                    # Remover Haunted Willow e manter La Calaca
                    sed -i '69s/La Calaca\/Haunted Willow/La Calaca/' $HTML
                    echo "Haunted Willow foi removido."
                else
                    echo "Opção inválida."
                fi
            elif [[ $(sed '69q;d' "$HTML") == *"La Calaca"* ]]; then
                sed -i '69s/La Calaca/Boss Not Found/' $HTML
                sed -i '69s/color: rgb(0, 255, 0);/color: red;/' $HTML
                echo "O status de North America 1 foi alterado"
            elif [[ $(sed '64q;d' "$HTML") == *"Haunted Willow"* ]]; then
                sed -i '69s/Haunted Willow/Boss Not Found/' $HTML
                sed -i '69s/color: rgb(0, 255, 0);/color: red;/' $HTML
            fi

	        att-repo
            break;;
        3)
            echo "Você selecionou North America 3"

            if [[ $(sed '74q;d' "$HTML") == *"La Calaca/Haunted Willow"* ]]; then
            echo "Ambos os bosses estão presentes. Qual você deseja remover?"
            echo "1) La Calaca"
            echo "2) Haunted Willow"
            read -p "Selecione uma opção (1 ou 2): " boss_option

                if [[ $boss_option -eq 1 ]]; then
                    # Remover La Calaca e manter Haunted Willow
                    sed -i '74s/La Calaca\/Haunted Willow/Haunted Willow/' $HTML
                    echo "La Calaca foi removido."
                elif [[ $boss_option -eq 2 ]]; then
                    # Remover Haunted Willow e manter La Calaca
                    sed -i '74s/La Calaca\/Haunted Willow/La Calaca/' $HTML
                    echo "Haunted Willow foi removido."
                else
                    echo "Opção inválida."
                fi
            elif [[ $(sed '74q;d' "$HTML") == *"La Calaca"* ]]; then
                sed -i '74s/La Calaca/Boss Not Found/' $HTML
                sed -i '74s/color: rgb(0, 255, 0);/color: red;/' $HTML
                echo "O status de North America 1 foi alterado"
            elif [[ $(sed '74q;d' "$HTML") == *"Haunted Willow"* ]]; then
                sed -i '74s/Haunted Willow/Boss Not Found/' $HTML
                sed -i '74s/color: rgb(0, 255, 0);/color: red;/' $HTML
            fi
	        att-repo
            break;;
        4)
            echo "Você selecionou North America 4"

	    # Alterando o status de "Boss Not Found" para "Spawned" e mudando a cor para verde
            sed -i '78s/Spawned/Boss Not Found/' $HTML
            sed -i '78s/color: rgb(0, 255, 0);/color: red;/' $HTML

            echo "O status de North America 4 foi alterado para 'Boss Not Found' e a cor para red."
	        att-repo
            break;;
        5)
            echo "Você selecionou North America 5"

	    # Alterando o status de "Boss Not Found" para "Spawned" e mudando a cor para verde
            sed -i '64s/Spawned/Boss Not Found/' $HTML
            sed -i '64s/color: rgb(0, 255, 0);/color: red;/' $HTML

            echo "O status de North America 5 foi alterado para 'Boss Not Found' e a cor para red."
	        att-repo
            break;;
        6)
            echo "Você selecionou North America 6"

	    # Alterando o status de "Boss Not Found" para "Spawned" e mudando a cor para verde
            sed -i '86s/Spawned/Boss Not Found/' $HTML
            sed -i '86s/color: rgb(0, 255, 0);/color: red;/' $HTML

            echo "O status de North America 6 foi alterado para 'Boss Not Found' e a cor para red."
	        att-repo
            break;;
        7)
            echo "Você selecionou South America 1"

	    # Alterando o status de "Boss Not Found" para "Spawned" e mudando a cor para verde
            sed -i '93s/Spawned/Boss Not Found/' $HTML
            sed -i '93s/color: rgb(0, 255, 0);/color: red;/' $HTML

            echo "O status de South America 1 foi alterado para 'Boss Not Found' e a cor para red."
	        att-repo
            break;;
        8)
            echo "Você selecionou South America 2"

	    # Alterando o status de "Boss Not Found" para "Spawned" e mudando a cor para verde
            sed -i '97s/Spawned/Boss Not Found/' $HTML
            sed -i '97s/color: rgb(0, 255, 0);/color: red;/' $HTML

            echo "O status de South America 2 foi alterado para 'Boss Not Found' e a cor para red."
	        att-repo
            break;;
        9)
            echo "Você selecionou South America 3"

	    # Alterando o status de "Boss Not Found" para "Spawned" e mudando a cor para verde
            sed -i '101s/Spawned/Boss Not Found/' $HTML
            sed -i '101s/color: rgb(0, 255, 0);/color: red;/' $HTML

            echo "O status de South America 3 foi alterado para 'Boss Not Found' e a cor para red."
	        att-repo
            break;;
        10)
            echo "Você selecionou South America 4"

	    # Alterando o status de "Boss Not Found" para "Spawned" e mudando a cor para verde
            sed -i '105s/Spawned/Boss Not Found/' $HTML
            sed -i '105s/color: rgb(0, 255, 0);/color: red;/' $HTML

            echo "O status de South America 4 foi alterado para 'Boss Not Found' e a cor para red."
	        att-repo
            break;;
        11)
            echo "Você selecionou South America 5"

	    # Alterando o status de "Boss Not Found" para "Spawned" e mudando a cor para verde
            sed -i '109s/Spawned/Boss Not Found/' $HTML
            sed -i '109s/color: rgb(0, 255, 0);/color: red;/' $HTML

            echo "O status de South America 5 foi alterado para 'Boss Not Found' e a cor para red."
	        att-repo
            break;;
        12)
            echo "Você selecionou South America 6"

	    # Alterando o status de "Boss Not Found" para "Spawned" e mudando a cor para verde
            sed -i '113s/Spawned/Boss Not Found/' $HTML
            sed -i '113s/color: rgb(0, 255, 0);/color: red;/' $HTML

            echo "O status de South America 6 foi alterado para 'Boss Not Found e a cor para red."
	        att-repo
            break;;
        13)
            echo "Você selecionou South America 7"

	    # Alterando o status de "Boss Not Found" para "Spawned" e mudando a cor para verde
            sed -i '117s/Spawned/Boss Not Found/' $HTML
            sed -i '117s/color: rgb(0, 255, 0);/color: red;/' $HTML

            echo "O status de South America 7 foi alterado para 'Boss Not Found' e a cor para red."
	        att-repo
            break;;
        14)
            echo "Você selecionou South America 8"

	    # Alterando o status de "Boss Not Found" para "Spawned" e mudando a cor para verde
            sed -i '121s/Spawned/Boss Not Found/' $HTML
            sed -i '121s/color: rgb(0, 255, 0);/color: red;/' $HTML

            echo "O status de South America 8 foi alterado para 'Boss Not Found' e a cor para red."
	        att-repo
            break;;
        15)
            echo "Você selecionou Europe 1"

	    # Alterando o status de "Boss Not Found" para "Spawned" e mudando a cor para verde
            sed -i '128s/Spawned/Boss Not Found/' $HTML
            sed -i '128s/color: rgb(0, 255, 0);/color: red;/' $HTML

            echo "O status de Europe 1 foi alterado para 'Boss Not Found' e a cor para red."
	        att-repo
            break;;
        16)
            echo "Você selecionou Europe 2"

	    # Alterando o status de "Boss Not Found" para "Spawned" e mudando a cor para verde
            sed -i '132s/Spawned/Boss Not Found/' $HTML
            sed -i '132s/color: rgb(0, 255, 0);/color: red;/' $HTML

            echo "O status de Europe 2 foi alterado para 'Boss Not Found' e a cor para red."
	        att-repo
            break;;
        17)
            echo "Você selecionou Europe 3"

	    # Alterando o status de "Boss Not Found" para "Spawned" e mudando a cor para verde
            sed -i '136s/Spawned/Boss Not Found/' $HTML
            sed -i '136s/color: rgb(0, 255, 0);/color: red;/' $HTML

            echo "O status de Europe 3 foi alterado para 'Boss Not Found' e a cor para red."
	        att-repo
            break;;
        18)
            echo "Você selecionou Europe 4"

	    # Alterando o status de "Boss Not Found" para "Spawned" e mudando a cor para verde
            sed -i '140s/Spawned/Boss Not Found/' $HTML
            sed -i '140s/color: rgb(0, 255, 0);/color: red;/' $HTML

            echo "O status de Europe 4 foi alterado para 'Boss Not Found' e a cor para red."
	        att-repo
            break;;
        19)
            echo "Você selecionou Europe 5"

	    # Alterando o status de "Boss Not Found" para "Spawned" e mudando a cor para verde
            sed -i '144s/Spawned/Boss Not Found/' $HTML
            sed -i '144s/color: rgb(0, 255, 0);/color: red;/' $HTML

            echo "O status de Europa 5 foi alterado para 'Boss Not Found' e a cor para red."
	        att-repo
            break;;
        20)
            echo "Você selecionou Europe 6"

	    # Alterando o status de "Boss Not Found" para "Spawned" e mudando a cor para verde
            sed -i '148s/Spawned/Boss Not Found/' $HTML
            sed -i '148s/color: rgb(0, 255, 0);/color: red;/' $HTML

            echo "O status de Europa 6 foi alterado para 'Boss Not Found' e a cor para red."
	        att-repo
            break;;
        21)
            echo "Você selecionou Asia 1"

	    # Alterando o status de "Boss Not Found" para "Spawned" e mudando a cor para verde
            sed -i '155s/Spawned/Boss Not Found/' $HTML
            sed -i '155s/color: rgb(0, 255, 0);/color: red;/' $HTML

            echo "O status de Asia 1 foi alterado para 'Boss Not Found' e a cor para red."
	        att-repo
            break;;
        22)
            echo "Você selecionou Asia 2"

	    # Alterando o status de "Boss Not Found" para "Spawned" e mudando a cor para verde
            sed -i '159s/Spawned/Boss Not Found/' $HTML
            sed -i '159s/color: rgb(0, 255, 0);/color: red;/' $HTML

            echo "O status de Asia 2 foi alterado para 'Boss Not Found' e a cor para red."
	        att-repo
            break;;
        23)
            echo "Você selecionou Asia 3"

	    # Alterando o status de "Boss Not Found" para "Spawned" e mudando a cor para verde
            sed -i '163s/Spawned/Boss Not Found/' $HTML
            sed -i '163s/color: rgb(0, 255, 0);/color: red;/' $HTML

            echo "O status de Asia 3 foi alterado para 'Boss Not Found' e a cor para red."
	        att-repo
            break;;
        24)
            echo "Você selecionou Asia 4"

	    # Alterando o status de "Boss Not Found" para "Spawned" e mudando a cor para verde
            sed -i '167s/Spawned/Boss Not Found/' $HTML
            sed -i '167s/color: rgb(0, 255, 0);/color: red;/' $HTML

            echo "O status de Asia 4 foi alterado para 'Boss Not Found' e a cor para red."
	        att-repo
            break;;
	    25)
	        cd $HOME/Rucoy-bosses/
	        . rank
	        break;;
        *)
           
            echo "Opção inválida. Por favor, tente novamente."
            ;;
    esac
done
